spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydatabase
    username: root
    password: 123
  application:
    name: user-service
mybatis:
  type-aliases-package: cn.itcast.user.pojo
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka